apiVersion: v1
kind: Service
metadata: 
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  selector:
    service: reverseproxy
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080   # the service port
    targetPort: 8080  # the target containerPort